-- backend/schema.sql (Oracle version)
-- Run this once against your Oracle database (e.g. via SQL*Plus, SQL Developer,
-- or "sqlplus user/pass@connectString @schema.sql") to create the tables.

-- ---------------------------------------------------------------
-- Table 1: users (for login)
-- ---------------------------------------------------------------
CREATE TABLE users (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      VARCHAR2(100) NOT NULL UNIQUE,
  password      VARCHAR2(255) NOT NULL,
  display_name  VARCHAR2(150) DEFAULT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO users u
USING (SELECT 'admin' AS username, 'admin123' AS password, 'Administrator' AS display_name FROM dual) src
ON (u.username = src.username)
WHEN NOT MATCHED THEN
  INSERT (username, password, display_name) VALUES (src.username, src.password, src.display_name);

-- ---------------------------------------------------------------
-- Table 2: atm_sites — matches the ATMID / Adress / IP_CAM / Video_IP
-- columns from the checklist sheet. This is the fixed site info that
-- does NOT change day to day. "email" is kept but not shown on the
-- checklist screen — it's only used to send the fault-alert email.
-- ---------------------------------------------------------------
CREATE TABLE atm_sites (
  atmid       VARCHAR2(20) PRIMARY KEY,     -- ATMID
  adress      VARCHAR2(200) NOT NULL,       -- Adress
  ip_cam      VARCHAR2(50)  DEFAULT NULL,   -- IP_CAM
  video_ip    VARCHAR2(50)  DEFAULT NULL,   -- Video_IP
  email       VARCHAR2(150) DEFAULT NULL,   -- not on screen, used for alert emails
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

MERGE INTO atm_sites s
USING (SELECT '01000100' AS atmid, 'Pv oil Naxay' AS adress, '10.0.1.3' AS ip_cam, '10.0.1.4' AS video_ip, 'pvoilnaxay@example.com' AS email FROM dual
       UNION ALL
       SELECT '01000200', 'Asain Mall', '10.0.1.11', '10.0.1.12', 'asainmall@example.com' FROM dual) src
ON (s.atmid = src.atmid)
WHEN NOT MATCHED THEN
  INSERT (atmid, adress, ip_cam, video_ip, email)
  VALUES (src.atmid, src.adress, src.ip_cam, src.video_ip, src.email)
WHEN MATCHED THEN
  UPDATE SET s.adress = src.adress;

-- ---------------------------------------------------------------
-- Table 3 (reference only — NOT used yet): checklist_records
-- The running app currently saves each day's checkboxes as a JSON
-- file in backend/data/<date>.json, not into the database. This
-- table is here so you can switch to Oracle storage later if you
-- want to; it mirrors exactly the 8 checkboxes shown on the sheet
-- (Cam_conect, Cam_work, DRV_conect, Cam_save — each with its own
-- "connect" and "disconnect" box, independent of each other).
-- ---------------------------------------------------------------
CREATE TABLE checklist_records (
  id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_date           DATE NOT NULL,
  atmid                 VARCHAR2(20) NOT NULL,
  cam_conect_connect    NUMBER(1) DEFAULT 0 CHECK (cam_conect_connect IN (0,1)),
  cam_conect_disconnect NUMBER(1) DEFAULT 0 CHECK (cam_conect_disconnect IN (0,1)),
  cam_work_connect      NUMBER(1) DEFAULT 0 CHECK (cam_work_connect IN (0,1)),
  cam_work_disconnect   NUMBER(1) DEFAULT 0 CHECK (cam_work_disconnect IN (0,1)),
  drv_conect_connect    NUMBER(1) DEFAULT 0 CHECK (drv_conect_connect IN (0,1)),
  drv_conect_disconnect NUMBER(1) DEFAULT 0 CHECK (drv_conect_disconnect IN (0,1)),
  cam_save_connect      NUMBER(1) DEFAULT 0 CHECK (cam_save_connect IN (0,1)),
  cam_save_disconnect   NUMBER(1) DEFAULT 0 CHECK (cam_save_disconnect IN (0,1)),
  checked_by            VARCHAR2(100) DEFAULT NULL,
  created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_checklist_atmid FOREIGN KEY (atmid) REFERENCES atm_sites(atmid),
  CONSTRAINT uniq_date_atm UNIQUE (record_date, atmid)
);

-- ---------------------------------------------------------------
-- Table 4: audit_logs — records every important action (per spec 7.3)
-- Note: the spec's field is called "timestamp", but that word is
-- reserved in Oracle SQL, so this column is named "event_time" instead.
-- ---------------------------------------------------------------
CREATE TABLE audit_logs (
  audit_id      VARCHAR2(36) PRIMARY KEY,   -- UUID, generated by the app
  user_id       VARCHAR2(50),               -- username of who did it
  action_type   VARCHAR2(50) NOT NULL,      -- LOGIN, CREATE_ATM, UPDATE_ATM, SUBMIT_INSPECTION
  target_ref    VARCHAR2(50),               -- e.g. ATMID, or the inspection date
  ip_address    VARCHAR2(50),               -- client IP
  event_time    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
